# Netlify Build Configuration

[build]
  command = "npm run build"  # Build command to generate the app
  publish = "dist"           # Folder where the built app resides
  functions = "netlify/functions"  # Serverless functions directory

[build.environment]
  NODE_VERSION = "20"        # Set Node.js version for the build process

# Redirects for Single-Page Application (SPA)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Handle payment intent creation specifically
[[redirects]]
  from = "/create-payment-intent"
  to = "/.netlify/functions/api/create-payment-intent"
  status = 200
  force = true

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # MUST be true to enable client-side routing

# Headers configuration
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache JS files for 1 year
    Content-Type = "application/javascript"               # Ensure JS files have correct MIME type

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache CSS files for 1 year
    Content-Type = "text/css"                             # Explicit MIME type for CSS

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"                            # Prevent caching of index.html for routing

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache assets for 1 year

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"                     # Allow cross-origin requests
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, X-Agent-ID, Authorization"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/widget.js"
  [headers.values]
    Cache-Control = "no-cache"
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"