# Netlify Build Configuration

[build]
  command = "npm run build"  # The command to build your app
  publish = "dist"           # The folder to publish after build (Vite's default build output folder)

[build.environment]
  NODE_VERSION = "20"        # Use Node.js version 20 (adjust based on your needs)

# Redirects for Single-Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Force all routes to be handled by the index.html for React Router

# Headers configuration
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache JavaScript files for a year
    Content-Type = "application/javascript"               # Set Content-Type for JS files

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache CSS files for a year

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"                            # Ensure index.html is not cached for fresh routing

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"               # Explicit Content-Type for JS in assets folder

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"                     # Allow cross-origin requests for all routes
