# Netlify Build Configuration

[build]
  command = "npm run build"  # Build command to generate the app
  publish = "dist"           # Folder where the built app resides

[build.environment]
  NODE_VERSION = "20"        # Set Node.js version for the build process

# Redirects for Single-Page Application (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true  # Ensure all routes are handled by React Router (if needed)

# Headers configuration
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache JS files for 1 year
    Content-Type = "application/javascript"               # Ensure JS files have correct MIME type

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"  # Cache CSS files for 1 year

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"                            # Prevent caching of index.html for routing

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"               # Explicit MIME type for JS in assets folder

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"                             # Explicit MIME type for CSS in assets folder

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"                     # Allow cross-origin requests for all routes
